<div style="border:2px solid black; padding:10px;">
    <h3>Nhóm 15</h3>
    <h1 style='color:red;text-align:center;font-size:30px'>Chủ đề: Phân tích về doanh thu phim<b></b></h1>
</div>

<h3>Danh sách thành viên</h3>
<li> Nguyễn Quốc Hưng - 21120464 </li>
<li> Đoàn Đức Hữu - 21120465 </li>
<li> Võ Minh Khuê - 21120486</li>
<li> Hồ Trọng Lễ - 21120494</li>

<h1 style='color:blue;text-align:center;font-size:30px'><b>Phần I - Thu thập dữ liệu</b></h1>

# Import thư viện

In [1]:

import pandas as pd

## Thu nhập thông tin phim từ năm 1990 đến năm 2020

In [19]:
!cd boxoffice_crawler/boxoffice_crawler/ && scrapy crawl BoxOfficeMojo

### Đọc file dữ liệu

In [3]:
df = pd.read_csv(
    './boxoffice_crawler/boxoffice_crawler/boxoffice_1990_2022.csv', encoding='latin1')
df.head(20)

,title,domestic_revenue,world_revenue,distributor,opening_revenue,opening_theaters,budget,MPAA,genres,running_time,in_release,release_date
0,Batman Returns,"$162,831,698","$266,831,698",Warner Bros.,"$45,687,711","2,644","$80,000,000",PG-13,"Action,Crime,Fantasy",126.0,196,19/06/1992
1,Coupe de Ville,"$715,983","$715,983",Universal Pictures,"$66,871",7,NaN,NaN,"Comedy,Drama",99.0,298,09/03/1990
2,C'est la vie,"$805,472","$805,472",The Samuel Goldwyn Company,"$18,749",2,NaN,NaN,"Comedy,Drama,Romance",110.0,63,02/11/1990
3,Waiting for the Light,"$808,690","$808,690",Triumph Releasing Corporation,"$334,748",149,NaN,NaN,Comedy,94.0,63,02/11/1990
4,Atlantis: The Lost Empire,"$84,056,472","$186,053,725",Walt Disney Studios Motion Pictures,"$329,011",2,"$120,000,000",PG,"Action,Adventure,Animation,Family,Fantasy,Sci-Fi",95.0,210,NaN
5,Evolution,"$38,345,494","$98,376,292",DreamWorks Distribution,"$13,408,351","2,611","$80,000,000",PG-13,"Comedy,Sci-Fi",101.0,207,08/06/2001
6,Jumanji,"$100,475,249","$100,475,249",Sony Pictures Entertainment (SPE),"$11,084,370","2,487","$65,000,000",PG,"Adventure,Comedy,Family,Fantasy",104.0,383,15/12/1995
7,The American President,"$60,079,496","$60,079,496",Sony Pictures Entertainment (SPE),"$10,014,558","1,508",NaN,PG-13,"Comedy,Drama,Romance",114.0,411,17/11/1995
8,Mulholland Drive,"$7,220,243","$20,117,339",Universal Pictures,"$587,591",66,NaN,R,"Drama,Mystery,Thriller",147.0,450,08/10/2001
9,Tombstone,"$56,505,065","$56,505,065",Walt Disney Studios Motion Pictures,"$6,454,752","1,504",NaN,R,"Biography,Drama,History,Western",130.0,373,24/12/1993
10,Heart and Souls,"$16,589,540","$16,589,540",Universal Pictures,"$4,322,250","1,275",NaN,PG-13,"Comedy,Drama,Fantasy,Romance",104.0,141,13/08/1993
11,The Phantom of the Opera,"$51,268,815","$154,648,887",Warner Bros.,"$4,001,890",622,"$70,000,000",PG-13,"Drama,Musical,Romance,Thriller",143.0,375,22/12/2004
12,The Brady Bunch Movie,"$46,576,136","$46,576,136",Paramount Pictures,"$14,827,066","1,822",NaN,PG-13,Comedy,90.0,318,17/02/1995
13,Teenage Mutant Ninja Turtles III,"$42,273,609","$42,273,609",New Line Cinema,"$12,419,597","2,087","$21,000,000",PG,"Action,Adventure,Comedy,Family,Fantasy,Sci-Fi",96.0,288,19/03/1993
14,Hardball,"$40,222,729","$44,102,389",Paramount Pictures,"$9,386,342","2,137","$32,000,000",PG-13,"Comedy,Drama,Sport",106.0,474,14/09/2001
15,Supercross,"$3,102,550","$3,344,431",Twentieth Century Fox,"$1,330,520","1,621",NaN,PG-13,"Action,Drama,Romance,Sport",80.0,137,17/08/2005
16,Life with Mikey,"$12,440,858","$12,440,858",Walt Disney Studios Motion Pictures,"$3,606,279","1,366",NaN,PG,"Comedy,Family",91.0,211,04/06/1993
17,Grizzly Man,"$3,178,403","$4,061,305",Lions Gate Films,"$269,131",29,NaN,R,"Biography,Documentary",103.0,147,12/08/2005
18,Rize,"$3,336,391","$4,646,889",Lions Gate Films,"$1,574,787",352,NaN,PG-13,"Documentary,Music",86.0,191,24/06/2005
19,Malena,"$3,448,233","$14,493,284",Miramax,"$62,282",33,NaN,R,"Drama,Romance,War",108.0,375,22/12/2000